name: Create release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        id: release
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      # https://github.com/anothrNick/github-tag-action
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # v1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CUSTOM_TAG: ${{ steps.release.outputs.new_tag }}