name: Deploy

on:
  push:
    branches: ["main"]
  
jobs:
  deploy-qa:
    name: Deploy

    runs-on: ubuntu-latest

    environment: QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying QA..."

  deploy-demo:
    name: Deploy

    runs-on: ubuntu-latest

    environment: Demo

    needs: [deploy-qa]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying Demo..."

  deploy-live:
    name: Deploy

    runs-on: ubuntu-latest

    environment: Live

    needs: [deploy-qa]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying Live..."