name: Deploy

on:
  push:
    branches: ["main"]
  
jobs:
  deploy-qa:
    name: Deploy

    runs-on: ubuntu-latest

    environment: QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying QA..."

  deploy:
    name: Deploy to ${{ matrix.environment }}

    runs-on: ubuntu-latest

    environment: Live

    needs: [deploy-qa]

    strategy:
      matrix:
        environment: [Demo, Live] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying ${{ matrix.environment }}..."