name: Publish helm

on:
  release:
    types: [published]

jobs:
  publish-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Publish helm
        run:
          echo "Publishing helm chart for release ${{ github.event.release.tag_name }}"